global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app'
    static_configs:
      - targets: ['employes-service:8080']  # Assume app exposes metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']  # Use redis-exporter if needed