// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: employee_service.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApiResponse is a generic response wrapper for all API calls.
type ApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "success" or "error"
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // Contains specific response data or error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_employee_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ApiResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApiResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// ErrorData represents the error message in error responses.
type ErrorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorData) Reset() {
	*x = ErrorData{}
	mi := &file_employee_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorData) ProtoMessage() {}

func (x *ErrorData) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorData.ProtoReflect.Descriptor instead.
func (*ErrorData) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Employee represents an employee entity.
type Employee struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MiddleName     *string                `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3,oneof" json:"middle_name,omitempty"`
	Phone          *string                `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	PersonalNumber *string                `protobuf:"bytes,6,opt,name=personal_number,json=personalNumber,proto3,oneof" json:"personal_number,omitempty"`
	Email          *string                `protobuf:"bytes,7,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Password       *string                `protobuf:"bytes,8,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Role           string                 `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"` // "admin", "hr", "manager", "employee"
	IsActive       bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DepartmentId   *uint64                `protobuf:"varint,11,opt,name=department_id,json=departmentId,proto3,oneof" json:"department_id,omitempty"`
	Position       *string                `protobuf:"bytes,12,opt,name=position,proto3,oneof" json:"position,omitempty"`
	ManagerId      *uint64                `protobuf:"varint,13,opt,name=manager_id,json=managerId,proto3,oneof" json:"manager_id,omitempty"`
	HireDate       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=hire_date,json=hireDate,proto3,oneof" json:"hire_date,omitempty"`
	FireDate       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=fire_date,json=fireDate,proto3,oneof" json:"fire_date,omitempty"`
	Birthday       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Address        *string                `protobuf:"bytes,17,opt,name=address,proto3,oneof" json:"address,omitempty"`
	VacationDays   uint64                 `protobuf:"varint,18,opt,name=vacation_days,json=vacationDays,proto3" json:"vacation_days,omitempty"`
	SickDays       uint64                 `protobuf:"varint,19,opt,name=sick_days,json=sickDays,proto3" json:"sick_days,omitempty"`
	Status         string                 `protobuf:"bytes,20,opt,name=status,proto3" json:"status,omitempty"` // "active", "fired", "suspended"
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_employee_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{2}
}

func (x *Employee) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Employee) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Employee) GetMiddleName() string {
	if x != nil && x.MiddleName != nil {
		return *x.MiddleName
	}
	return ""
}

func (x *Employee) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *Employee) GetPersonalNumber() string {
	if x != nil && x.PersonalNumber != nil {
		return *x.PersonalNumber
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Employee) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Employee) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Employee) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Employee) GetDepartmentId() uint64 {
	if x != nil && x.DepartmentId != nil {
		return *x.DepartmentId
	}
	return 0
}

func (x *Employee) GetPosition() string {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return ""
}

func (x *Employee) GetManagerId() uint64 {
	if x != nil && x.ManagerId != nil {
		return *x.ManagerId
	}
	return 0
}

func (x *Employee) GetHireDate() *timestamppb.Timestamp {
	if x != nil {
		return x.HireDate
	}
	return nil
}

func (x *Employee) GetFireDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FireDate
	}
	return nil
}

func (x *Employee) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *Employee) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *Employee) GetVacationDays() uint64 {
	if x != nil {
		return x.VacationDays
	}
	return 0
}

func (x *Employee) GetSickDays() uint64 {
	if x != nil {
		return x.SickDays
	}
	return 0
}

func (x *Employee) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Employee) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Employee) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Department represents a department entity.
type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ParentId      *uint64                `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	HeadId        *uint64                `protobuf:"varint,5,opt,name=head_id,json=headId,proto3,oneof" json:"head_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_employee_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{3}
}

func (x *Department) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Department) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *Department) GetHeadId() uint64 {
	if x != nil && x.HeadId != nil {
		return *x.HeadId
	}
	return 0
}

func (x *Department) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Department) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DepartmentForm represents the input for creating/updating a department.
type DepartmentForm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ParentId      *uint64                `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	HeadId        *uint64                `protobuf:"varint,4,opt,name=head_id,json=headId,proto3,oneof" json:"head_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentForm) Reset() {
	*x = DepartmentForm{}
	mi := &file_employee_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentForm) ProtoMessage() {}

func (x *DepartmentForm) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentForm.ProtoReflect.Descriptor instead.
func (*DepartmentForm) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{4}
}

func (x *DepartmentForm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentForm) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *DepartmentForm) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *DepartmentForm) GetHeadId() uint64 {
	if x != nil && x.HeadId != nil {
		return *x.HeadId
	}
	return 0
}

// LoginRequest represents the input for authentication.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_employee_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse contains the JWT tokens.
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_employee_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// VacationRequest represents a request to add vacation days.
type VacationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          uint64                 `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VacationRequest) Reset() {
	*x = VacationRequest{}
	mi := &file_employee_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacationRequest) ProtoMessage() {}

func (x *VacationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacationRequest.ProtoReflect.Descriptor instead.
func (*VacationRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{7}
}

func (x *VacationRequest) GetDays() uint64 {
	if x != nil {
		return x.Days
	}
	return 0
}

// GetEmployeesRequest contains filters for querying employees.
type GetEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *string                `protobuf:"bytes,1,opt,name=role,proto3,oneof" json:"role,omitempty"`
	DepartmentId  *uint64                `protobuf:"varint,2,opt,name=department_id,json=departmentId,proto3,oneof" json:"department_id,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeesRequest) Reset() {
	*x = GetEmployeesRequest{}
	mi := &file_employee_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeesRequest) ProtoMessage() {}

func (x *GetEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeesRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetEmployeesRequest) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

func (x *GetEmployeesRequest) GetDepartmentId() uint64 {
	if x != nil && x.DepartmentId != nil {
		return *x.DepartmentId
	}
	return 0
}

func (x *GetEmployeesRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

// GetEmployeesResponse contains a list of employees.
type GetEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeesResponse) Reset() {
	*x = GetEmployeesResponse{}
	mi := &file_employee_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeesResponse) ProtoMessage() {}

func (x *GetEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeesResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

// GetDepartmentsResponse contains a list of departments.
type GetDepartmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departments   []*Department          `protobuf:"bytes,1,rep,name=departments,proto3" json:"departments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentsResponse) Reset() {
	*x = GetDepartmentsResponse{}
	mi := &file_employee_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentsResponse) ProtoMessage() {}

func (x *GetDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*GetDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetDepartmentsResponse) GetDepartments() []*Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

// GetEmployeeByIDRequest contains the ID for retrieving an employee.
type GetEmployeeByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIDRequest) Reset() {
	*x = GetEmployeeByIDRequest{}
	mi := &file_employee_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIDRequest) ProtoMessage() {}

func (x *GetEmployeeByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIDRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIDRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetEmployeeByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// UpdateEmployeeRequest contains the ID and employee data for updating.
type UpdateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Employee      *Employee              `protobuf:"bytes,2,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeRequest) Reset() {
	*x = UpdateEmployeeRequest{}
	mi := &file_employee_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeRequest) ProtoMessage() {}

func (x *UpdateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateEmployeeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmployeeRequest) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

// DeleteEmployeeRequest contains the ID for deleting an employee.
type DeleteEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeRequest) Reset() {
	*x = DeleteEmployeeRequest{}
	mi := &file_employee_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeRequest) ProtoMessage() {}

func (x *DeleteEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteEmployeeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// RequestVacationRequest contains the ID and vacation data.
type RequestVacationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vacation      *VacationRequest       `protobuf:"bytes,2,opt,name=vacation,proto3" json:"vacation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVacationRequest) Reset() {
	*x = RequestVacationRequest{}
	mi := &file_employee_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVacationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVacationRequest) ProtoMessage() {}

func (x *RequestVacationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVacationRequest.ProtoReflect.Descriptor instead.
func (*RequestVacationRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{14}
}

func (x *RequestVacationRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestVacationRequest) GetVacation() *VacationRequest {
	if x != nil {
		return x.Vacation
	}
	return nil
}

// GetDepartmentByIDRequest contains the ID for retrieving a department.
type GetDepartmentByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentByIDRequest) Reset() {
	*x = GetDepartmentByIDRequest{}
	mi := &file_employee_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentByIDRequest) ProtoMessage() {}

func (x *GetDepartmentByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentByIDRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetDepartmentByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// UpdateDepartmentRequest contains the ID and department data for updating.
type UpdateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Department    *DepartmentForm        `protobuf:"bytes,2,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentRequest) Reset() {
	*x = UpdateDepartmentRequest{}
	mi := &file_employee_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentRequest) ProtoMessage() {}

func (x *UpdateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDepartmentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDepartmentRequest) GetDepartment() *DepartmentForm {
	if x != nil {
		return x.Department
	}
	return nil
}

// DeleteDepartmentRequest contains the ID for deleting a department.
type DeleteDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentRequest) Reset() {
	*x = DeleteDepartmentRequest{}
	mi := &file_employee_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentRequest) ProtoMessage() {}

func (x *DeleteDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_employee_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteDepartmentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_employee_service_proto protoreflect.FileDescriptor

const file_employee_service_proto_rawDesc = "" +
	"\n" +
	"\x16employee_service.proto\x12\x10employee_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/api/annotations.proto\"c\n" +
	"\vApiResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\"!\n" +
	"\tErrorData\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xf1\a\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12$\n" +
	"\vmiddle_name\x18\x04 \x01(\tH\x00R\n" +
	"middleName\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x05 \x01(\tH\x01R\x05phone\x88\x01\x01\x12,\n" +
	"\x0fpersonal_number\x18\x06 \x01(\tH\x02R\x0epersonalNumber\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\a \x01(\tH\x03R\x05email\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\b \x01(\tH\x04R\bpassword\x88\x01\x01\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12(\n" +
	"\rdepartment_id\x18\v \x01(\x04H\x05R\fdepartmentId\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\f \x01(\tH\x06R\bposition\x88\x01\x01\x12\"\n" +
	"\n" +
	"manager_id\x18\r \x01(\x04H\aR\tmanagerId\x88\x01\x01\x12<\n" +
	"\thire_date\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampH\bR\bhireDate\x88\x01\x01\x12<\n" +
	"\tfire_date\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampH\tR\bfireDate\x88\x01\x01\x12;\n" +
	"\bbirthday\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\n" +
	"R\bbirthday\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x11 \x01(\tH\vR\aaddress\x88\x01\x01\x12#\n" +
	"\rvacation_days\x18\x12 \x01(\x04R\fvacationDays\x12\x1b\n" +
	"\tsick_days\x18\x13 \x01(\x04R\bsickDays\x12\x16\n" +
	"\x06status\x18\x14 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_middle_nameB\b\n" +
	"\x06_phoneB\x12\n" +
	"\x10_personal_numberB\b\n" +
	"\x06_emailB\v\n" +
	"\t_passwordB\x10\n" +
	"\x0e_department_idB\v\n" +
	"\t_positionB\r\n" +
	"\v_manager_idB\f\n" +
	"\n" +
	"_hire_dateB\f\n" +
	"\n" +
	"_fire_dateB\v\n" +
	"\t_birthdayB\n" +
	"\n" +
	"\b_address\"\xb7\x02\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x04 \x01(\x04H\x01R\bparentId\x88\x01\x01\x12\x1c\n" +
	"\ahead_id\x18\x05 \x01(\x04H\x02R\x06headId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_parent_idB\n" +
	"\n" +
	"\b_head_id\"\xb5\x01\n" +
	"\x0eDepartmentForm\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x04H\x01R\bparentId\x88\x01\x01\x12\x1c\n" +
	"\ahead_id\x18\x04 \x01(\x04H\x02R\x06headId\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_parent_idB\n" +
	"\n" +
	"\b_head_id\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"%\n" +
	"\x0fVacationRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x04R\x04days\"\x9b\x01\n" +
	"\x13GetEmployeesRequest\x12\x17\n" +
	"\x04role\x18\x01 \x01(\tH\x00R\x04role\x88\x01\x01\x12(\n" +
	"\rdepartment_id\x18\x02 \x01(\x04H\x01R\fdepartmentId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x02R\x06status\x88\x01\x01B\a\n" +
	"\x05_roleB\x10\n" +
	"\x0e_department_idB\t\n" +
	"\a_status\"P\n" +
	"\x14GetEmployeesResponse\x128\n" +
	"\temployees\x18\x01 \x03(\v2\x1a.employee_service.EmployeeR\temployees\"X\n" +
	"\x16GetDepartmentsResponse\x12>\n" +
	"\vdepartments\x18\x01 \x03(\v2\x1c.employee_service.DepartmentR\vdepartments\"(\n" +
	"\x16GetEmployeeByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"_\n" +
	"\x15UpdateEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x126\n" +
	"\bemployee\x18\x02 \x01(\v2\x1a.employee_service.EmployeeR\bemployee\"'\n" +
	"\x15DeleteEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"g\n" +
	"\x16RequestVacationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12=\n" +
	"\bvacation\x18\x02 \x01(\v2!.employee_service.VacationRequestR\bvacation\"*\n" +
	"\x18GetDepartmentByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"k\n" +
	"\x17UpdateDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12@\n" +
	"\n" +
	"department\x18\x02 \x01(\v2 .employee_service.DepartmentFormR\n" +
	"department\")\n" +
	"\x17DeleteDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id2\xb1\f\n" +
	"\x0fEmployeeService\x12i\n" +
	"\tAuthLogin\x12\x1e.employee_service.LoginRequest\x1a\x1d.employee_service.ApiResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12`\n" +
	"\n" +
	"AuthLogout\x12\x16.google.protobuf.Empty\x1a\x1d.employee_service.ApiResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/api/v1/auth/logout\x12o\n" +
	"\fGetEmployees\x12%.employee_service.GetEmployeesRequest\x1a\x1d.employee_service.ApiResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/employees\x12i\n" +
	"\x0eCreateEmployee\x12\x1a.employee_service.Employee\x1a\x1d.employee_service.ApiResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/employees\x12{\n" +
	"\x10GetEmployeesByID\x12(.employee_service.GetEmployeeByIDRequest\x1a\x1d.employee_service.ApiResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/employees/{id}\x12\x82\x01\n" +
	"\x0eUpdateEmployee\x12'.employee_service.UpdateEmployeeRequest\x1a\x1d.employee_service.ApiResponse\"(\x82\xd3\xe4\x93\x02\":\bemployee\x1a\x16/api/v1/employees/{id}\x12x\n" +
	"\x0eDeleteEmployee\x12'.employee_service.DeleteEmployeeRequest\x1a\x1d.employee_service.ApiResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/employees/{id}\x12\x8d\x01\n" +
	"\x0fRequestVacation\x12(.employee_service.RequestVacationRequest\x1a\x1d.employee_service.ApiResponse\"1\x82\xd3\xe4\x93\x02+:\bvacation\"\x1f/api/v1/employees/{id}/vacation\x12d\n" +
	"\x0eGetDepartments\x12\x16.google.protobuf.Empty\x1a\x1d.employee_service.ApiResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/departments\x12s\n" +
	"\x10CreateDepartment\x12 .employee_service.DepartmentForm\x1a\x1d.employee_service.ApiResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/departments\x12\x80\x01\n" +
	"\x11GetDepartmentByID\x12*.employee_service.GetDepartmentByIDRequest\x1a\x1d.employee_service.ApiResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/departments/{id}\x12\x8a\x01\n" +
	"\x10UpdateDepartment\x12).employee_service.UpdateDepartmentRequest\x1a\x1d.employee_service.ApiResponse\",\x82\xd3\xe4\x93\x02&:\n" +
	"department\x1a\x18/api/v1/departments/{id}\x12~\n" +
	"\x10DeleteDepartment\x12).employee_service.DeleteDepartmentRequest\x1a\x1d.employee_service.ApiResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/departments/{id}B+Z)github.com/adamanr/employes_service/protob\x06proto3"

var (
	file_employee_service_proto_rawDescOnce sync.Once
	file_employee_service_proto_rawDescData []byte
)

func file_employee_service_proto_rawDescGZIP() []byte {
	file_employee_service_proto_rawDescOnce.Do(func() {
		file_employee_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_service_proto_rawDesc), len(file_employee_service_proto_rawDesc)))
	})
	return file_employee_service_proto_rawDescData
}

var file_employee_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_employee_service_proto_goTypes = []any{
	(*ApiResponse)(nil),              // 0: employee_service.ApiResponse
	(*ErrorData)(nil),                // 1: employee_service.ErrorData
	(*Employee)(nil),                 // 2: employee_service.Employee
	(*Department)(nil),               // 3: employee_service.Department
	(*DepartmentForm)(nil),           // 4: employee_service.DepartmentForm
	(*LoginRequest)(nil),             // 5: employee_service.LoginRequest
	(*LoginResponse)(nil),            // 6: employee_service.LoginResponse
	(*VacationRequest)(nil),          // 7: employee_service.VacationRequest
	(*GetEmployeesRequest)(nil),      // 8: employee_service.GetEmployeesRequest
	(*GetEmployeesResponse)(nil),     // 9: employee_service.GetEmployeesResponse
	(*GetDepartmentsResponse)(nil),   // 10: employee_service.GetDepartmentsResponse
	(*GetEmployeeByIDRequest)(nil),   // 11: employee_service.GetEmployeeByIDRequest
	(*UpdateEmployeeRequest)(nil),    // 12: employee_service.UpdateEmployeeRequest
	(*DeleteEmployeeRequest)(nil),    // 13: employee_service.DeleteEmployeeRequest
	(*RequestVacationRequest)(nil),   // 14: employee_service.RequestVacationRequest
	(*GetDepartmentByIDRequest)(nil), // 15: employee_service.GetDepartmentByIDRequest
	(*UpdateDepartmentRequest)(nil),  // 16: employee_service.UpdateDepartmentRequest
	(*DeleteDepartmentRequest)(nil),  // 17: employee_service.DeleteDepartmentRequest
	(*anypb.Any)(nil),                // 18: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),    // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 20: google.protobuf.Empty
}
var file_employee_service_proto_depIdxs = []int32{
	18, // 0: employee_service.ApiResponse.data:type_name -> google.protobuf.Any
	19, // 1: employee_service.Employee.hire_date:type_name -> google.protobuf.Timestamp
	19, // 2: employee_service.Employee.fire_date:type_name -> google.protobuf.Timestamp
	19, // 3: employee_service.Employee.birthday:type_name -> google.protobuf.Timestamp
	19, // 4: employee_service.Employee.created_at:type_name -> google.protobuf.Timestamp
	19, // 5: employee_service.Employee.updated_at:type_name -> google.protobuf.Timestamp
	19, // 6: employee_service.Department.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: employee_service.Department.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 8: employee_service.GetEmployeesResponse.employees:type_name -> employee_service.Employee
	3,  // 9: employee_service.GetDepartmentsResponse.departments:type_name -> employee_service.Department
	2,  // 10: employee_service.UpdateEmployeeRequest.employee:type_name -> employee_service.Employee
	7,  // 11: employee_service.RequestVacationRequest.vacation:type_name -> employee_service.VacationRequest
	4,  // 12: employee_service.UpdateDepartmentRequest.department:type_name -> employee_service.DepartmentForm
	5,  // 13: employee_service.EmployeeService.AuthLogin:input_type -> employee_service.LoginRequest
	20, // 14: employee_service.EmployeeService.AuthLogout:input_type -> google.protobuf.Empty
	8,  // 15: employee_service.EmployeeService.GetEmployees:input_type -> employee_service.GetEmployeesRequest
	2,  // 16: employee_service.EmployeeService.CreateEmployee:input_type -> employee_service.Employee
	11, // 17: employee_service.EmployeeService.GetEmployeesByID:input_type -> employee_service.GetEmployeeByIDRequest
	12, // 18: employee_service.EmployeeService.UpdateEmployee:input_type -> employee_service.UpdateEmployeeRequest
	13, // 19: employee_service.EmployeeService.DeleteEmployee:input_type -> employee_service.DeleteEmployeeRequest
	14, // 20: employee_service.EmployeeService.RequestVacation:input_type -> employee_service.RequestVacationRequest
	20, // 21: employee_service.EmployeeService.GetDepartments:input_type -> google.protobuf.Empty
	4,  // 22: employee_service.EmployeeService.CreateDepartment:input_type -> employee_service.DepartmentForm
	15, // 23: employee_service.EmployeeService.GetDepartmentByID:input_type -> employee_service.GetDepartmentByIDRequest
	16, // 24: employee_service.EmployeeService.UpdateDepartment:input_type -> employee_service.UpdateDepartmentRequest
	17, // 25: employee_service.EmployeeService.DeleteDepartment:input_type -> employee_service.DeleteDepartmentRequest
	0,  // 26: employee_service.EmployeeService.AuthLogin:output_type -> employee_service.ApiResponse
	0,  // 27: employee_service.EmployeeService.AuthLogout:output_type -> employee_service.ApiResponse
	0,  // 28: employee_service.EmployeeService.GetEmployees:output_type -> employee_service.ApiResponse
	0,  // 29: employee_service.EmployeeService.CreateEmployee:output_type -> employee_service.ApiResponse
	0,  // 30: employee_service.EmployeeService.GetEmployeesByID:output_type -> employee_service.ApiResponse
	0,  // 31: employee_service.EmployeeService.UpdateEmployee:output_type -> employee_service.ApiResponse
	0,  // 32: employee_service.EmployeeService.DeleteEmployee:output_type -> employee_service.ApiResponse
	0,  // 33: employee_service.EmployeeService.RequestVacation:output_type -> employee_service.ApiResponse
	0,  // 34: employee_service.EmployeeService.GetDepartments:output_type -> employee_service.ApiResponse
	0,  // 35: employee_service.EmployeeService.CreateDepartment:output_type -> employee_service.ApiResponse
	0,  // 36: employee_service.EmployeeService.GetDepartmentByID:output_type -> employee_service.ApiResponse
	0,  // 37: employee_service.EmployeeService.UpdateDepartment:output_type -> employee_service.ApiResponse
	0,  // 38: employee_service.EmployeeService.DeleteDepartment:output_type -> employee_service.ApiResponse
	26, // [26:39] is the sub-list for method output_type
	13, // [13:26] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_employee_service_proto_init() }
func file_employee_service_proto_init() {
	if File_employee_service_proto != nil {
		return
	}
	file_employee_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_employee_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_employee_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_employee_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_service_proto_rawDesc), len(file_employee_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_service_proto_goTypes,
		DependencyIndexes: file_employee_service_proto_depIdxs,
		MessageInfos:      file_employee_service_proto_msgTypes,
	}.Build()
	File_employee_service_proto = out.File
	file_employee_service_proto_goTypes = nil
	file_employee_service_proto_depIdxs = nil
}
