[server]
host = "0.0.0.0:8080"
grpc_host = "localhost:50051"
jwt_secret = "iLbsKq6ca5k5xBtmGNTqkcN7zSndnSu7g0d6I1kqVaU="
write_timeout = "10s"
read_timeout = "10s"
read_header_timeout = "10s"

[database]
host = "127.0.0.1:5431"  
user = "postgres"
password = "admin21"
database = "employee_dev"
port = "5431"  #

[redis]
redis_addr = "127.0.0.1:6379"  #redis:6379
redis_password = "redis_password123" 
redisdb = 0
access_token_ttl = "24h"
refresh_token_ttl = "168h"